Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,15 +1,24 @@
 #!/bin/bash
- #PBS -l nodes=1:ppn=16
- #PBS -l walltime=00:1:00
- #PBS -l walltime=00:10:00
- 
- # Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
- # 
- # This is the main file run by the brainlife.io orchestration system
- #
- # Author: Guiomar Niso
- mkdir -p out_dir
- # run the actual matlab code
-singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiledmatlab/main
+#PBS -l nodes=1:ppn=16,vmem=64gb,walltime=32:00:00
+#PBS -N noddi_matlab
 
+set -e
 
+# run noddi_matlab
+time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/noddi_matlab
+
+# cleanup and error check
+if [ -f noddi_fit_ficvf.nii ];then
+	mkdir noddi;
+	mv noddi_fit_ficvf.nii ./noddi/icvf.nii;
+	mv noddi_fit_fiso.nii ./noddi/isovf.nii;
+	mv noddi_fit_odi.nii ./noddi/od.nii;
+	gzip ./noddi/icvf.nii;
+	gzip ./noddi/isovf.nii;
+	gzip ./noddi/od.nii;
+#	gzip mask.nii;
+#	rm -rf *noddi_fit*;
+else
+	echo "output missing"
+	exit 1
+fi
